#$(firstword NAMES…)
# the same as $(word 1,NAMES)
# make
# main.c arch.c  Makefile start.c bootm.c
# firstword is main.c

S := main.c arch.c  Makefile start.c bootm.c



$(info $S)
$(info firstword is $(firstword $S))







