#$(join LIST1,LIST2)

# (join a b c,.c .o .s) 
# a.c b.o c.s 
# (join a b c,.c .o ) 
# a.c b.o c 




$(info (join a b c,.c .o .s) )

$(info $(join a b c,.c .o .s) )


$(info (join a b c,.c .o ) )

$(info $(join a b c,.c .o ) )



