# $(findstring FIND,IN)

# make
# main mm merere fdgdg 
# main
# mm mere trtr
# 



IN ?= main mm merere fdgdg 
T := $(findstring main,$(IN))

IN2 ?= mm mere trtr
T2 := $(findstring main,$(IN22))

$(info $(IN))
$(info $T)

$(info $(IN2))
$(info $(T2))


