#$(addprefix SUFFIX,NAMES…)

# main.c tool.c
# /src/main.c /src/tool.c
# /home/src/main.c /home/src/tool.c

T := main.c tool.c

$(info $T)
$(info $(addprefix /src/,$T))
$(info $(addprefix /home/src/,$T))

