#$(wordlist S,E,TEXT)

# make
# main.c arch.c  Makefile start.c bootm.c
# main.c arch.c
# Makefile start.c

S := main.c arch.c  Makefile start.c bootm.c



$(info $S)
$(info $(wordlist 1,2,$S))
$(info $(wordlist 3,4,$S))







