
#
# $(subst ee,EE,feet on the street)
#
#
# run make
# T
# fEEt on the strEEt
# fEEt on the strEEt12345
# ha ha ha

T := $(subst /src/,,/src/file.c /src/2.c)
#T12345 := ha ha ha


#$(info T)
$(info $(T))
#$(info $T12345)
#$(info $(T12345))


